services:
  - type: web
    name: fit-finance-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node /opt/render/project/dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
