services:
  - type: web
    name: fit-finance-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build && ls -la && ls -la dist/
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
